# -*- coding: utf-8 -*-
"""Moneyflowindex.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nryMyL4pLz70PgZF8-zM5WBzjwB4x7F1
"""

# Import Modules
import pandas as pd
import numpy as np
import csv
# Create Function
def moneyFlowIndex(filename,n):
# Read file
 data=pd.read_csv(filename, index_col ="Day")

# View dataframe

Open = data["Open"]
High = data["High"]
Low = data["Low"]
Close = data["Close"]
Volume = data["Volume"]

# Create dataframe
df = pd.DataFrame(data) 

# Calculate TypicalPrice
  
df['Typical Price'] = TypicalPrice 
df['Positive Money Flow']=0
df['Negative Money Flow']=0

MoneyFlow=TypicalPrice * Volume

# Calculate Positive/Negative Money Flow
df.loc[df['Typical Price'] > df['Typical Price'].shift(1), 'Positive Money Flow'] = MoneyFlow 
df.loc[df['Typical Price'] < df['Typical Price'].shift(1), 'Negative Money Flow'] = MoneyFlow

# Calculate Positive/Negative Money Flow sum
df['Positive Money Flow Sum'] = df['Positive Money Flow'].rolling(n).sum().astype('float64').round(2) 
df['Negative Money Flow Sum'] = df['Negative Money Flow'].rolling(n).sum().astype('float64').round(2) 

# Calculate Money Flow Index
MoneyRatio =df['Positive Money Flow Sum']/df['Negative Money Flow Sum'] 
MoneyFlowIndex=((MoneyRatio) / (1+MoneyRatio)) *100
df['Money Flow Index'] = MoneyFlowIndex 
df.to_csv('money flow index' + str(n) +'.csv')

moneyFlowIndex('sample.csv',16)